//
// Created by pospelov on 11.04.2020.
//

#ifndef CHECKERS_NETWORK_INCLUDE_SERVER_HPP_
#define CHECKERS_NETWORK_INCLUDE_SERVER_HPP_

class Server {};

#endif // CHECKERS_NETWORK_INCLUDE_SERVER_HPP_
